apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python-deployment
  labels:
    app: app-python

spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python

  minReadySeconds: 3

  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
      - name: app-python-container
        image: dianatomiya/devops:p_v1.0
        ports:
        - containerPort: 80