name: Go App CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "app_go/**"
      - ".github/workflows/go_ci.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "app_go/**"
      - ".github/workflows/go_ci.yml"

  
  workflow_dispatch:

env:
  WORKING_DIR: app_go

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.6"
      - name: Lint 
        uses: golangci/golangci-lint-action@v4
        with: 
            version: v1.54
            working-directory: ${{ env.WORKING_DIR }}
      - name: Test
        run: | 
          go test
        working-directory: ${{ env.WORKING_DIR }}
      - name: Snyk
        uses: snyk/actions/golang@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

  build-and-publish:
    timeout-minutes: 30
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ env.WORKING_DIR }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/python_devops:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          